baseURL = '/'
languageCode = 'en-us'
title = 'mktree'
theme = "cupper-hugo-theme"
[params]
  defaultDarkTheme = true
  logoAlt = "mktree"

publishDir = "docs"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "Changelog"
url = "/posts/changelog/"
weight = 2

[[menu.nav]]
name = "Language"
url = "/posts/language/"
weight = 2

[[menu.nav]]
name = "Reference"
url = "/posts/reference/"
weight = 2

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = false
    style = "monokai"

